{% set version = "2.18.1.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gmodels
  version: {{ version|replace("-", "_") }}

source:
  fn: gmodels_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/gmodels_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/gmodels/gmodels_{{ version }}.tar.gz
  sha256: da7d48021b7cd2fd8a7cd8d0bb9658b12342a32698a13877b25ca94aa03f1e95

build:
  noarch: generic
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-mass
    - r-gdata

  run:
    - r-base
    - r-mass
    - r-gdata

test:
  commands:
    - $R -e "library('gmodels')"  # [not win]
    - "\"%R%\" -e \"library('gmodels')\""  # [win]

about:
  home: http://www.sf.net/projects/r-gregmisc
  license: GPL-2.0-only
  summary: Various R programming tools for model fitting.
  license_family: GPL2

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
