travis:
  secure:
    BINSTAR_TOKEN: xk6rBLtEPO5eo6SVu8NDIpA0Wyt2QQY81BoGfjLgKSofyOo9MGZCpsH4BENbSR81sNLUVLdVhH1aoly6SWNfwfPCgbKcPxXN30St+nIxiuPQovsvQEhU30nlEuYi+ZxVweyM/6Ho1o1G19e+Xy8djp+xeW5FrVnd9GjQqCn8fuFp9pj/Nopr1GpRTBfjijd/M2w7ssrMaaMDh1F+fb0TLsYZKdOIT4AHC5jJ2WF5K2tYqksbiLeSAdLeYP4+oocJvYTrtMOCH+qGMukBrzqJb5erCqTlHNXQ81uQqFj88hsA5xG2bZilK6qqEiYJljCh578hcNv/cMJDWxJcB+jYuR25B9IG50LbphmpP3U3ujpv4hpbWNLQQqk5wx9inwSgBuBGV0PIiZsr6Qy6DIk1kacBOsq1+d2p28jpz7EnRC5uPoy9dS3GEOtvvJK17kcFd7nNlPO1iGI/JKSsW2p6IwQN9eyPP6xcrBDt+c7/651F/NIDEvjG9Xa53xnomgukZZfktQB8LrEK8C5m0mDf4WWxU2+rr9fz+m91BpwxIp/ql2XReG7QT2W2jTWXF6xoqZFJ2NL8udqM7qbSZEFCAkK0c2u0dbrwbtyx9ZcZ8z3Fbu/z3ceJkrig+KwQnfJ/N/gFoU+1qT+NdY8eHewWuLkeEMTUq4kTgdQ0FuB494o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
