appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: TAc5M4QSkYfLyz8DKddSPXMWcCEHs92z3PL1sEgMnef4uduwlPZtJ3iaFehxvqu/d2NVEpuF/WYs05jWv221FushD4CMGOTtHzXbFiFADXxkGewxP6d4OF+en5HFG5jkMTslC5+aIk6cvanjrJI41DHrw73XuswIieX1/wmTmsZ8R+sDUNltAox2Xr9HC3hoW59Jf394QK0dTQAlKw46V/kvm0Ccq92WGmFxCwcEjmPI6/4XhOaqTRI3Kc53RmyAIn3LyoJ3SR5h/zFzYLLFxunbtwLPru2TWYcrbkYjY4ujWsjIVw+nfvtkUCp8j214ikjY2+xF6d6Xugj+8Lba03U9jfdf9mBkfED8dZ2ro7WXdqSQcmusqWx4ens9o0yKXg85VZ7uWdCzvjhNl7dB2QKd/kMtmfuR7Kd1ogl7C2zXbtVzvWnz6PBb+c28f+z4PLKF1GgX/tIN7uabWl+1J+wsildq9UDM0LQXFPkvPxjS7kPEa8pIZIm7el/uVWrs877AItd+u+z6G5/EBl2ONkq6YCqcKq4ELsNVKuojGeF7RrMMAC+MVyBsWc3yrsQgKveaL7K6yIOj+g4cjcQi0B47LjxVAPTyBsOa1HrKqZ9l0mXMlC0wGAffouvfN4l1i/Fnf1H1GQHh01jGHFrHAEht31QluFLRVSrceo5tl1o=}
bot:
  automerge: true
